rds_endpoint: 'epicbk-rds.cjy24seigdl9.ap-southeast-1.rds.amazonaws.com'
rds_admin: 'imshakil'
rds_admin_password: 'yourRDSpassword'
db_name: 'bookstore'
db_user: 'theepicbook'
db_password: 'temp#123'
