db_host: epicbook-mysql-default-e27xb.mysql.database.azure.com
mysql_admin: devepicuser
mysql_admin_password: DevStrongPassword123!
db_name: bookstore
db_user: devepicuser
db_password: DevStrongPassword123!
db_ssl_mode: DISABLED
