project_repo_url: 'https://github.com/pravinmishraaws/theepicbook'
project_dir: '/home/{{ ansible_user }}/epicbook'
nginx_worker_processes: 'auto'
nginx_worker_connections: 1024
mysql_bind_address: '127.0.0.1'
mysql_socket: '/var/lib/mysql/mysql.sock'
