- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure default nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    backup: true
  notify: Restart nginx
  tags: ['nginx']

- name: Create nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: www-data
    group: adm
    mode: '0755'

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: ['nginx']

- name: Test Application locally
  ansible.builtin.uri:
    url: 'http://localhost:8080'
    return_content: true

- name: Test Application Public Access
  ansible.builtin.uri:
    url: 'http://{{ inventory_hostname }}'
    return_content: true
